# Default configuration for the device service.
# These values can be overridden by environment variables (e.g., DEVICE_SERVER__PORT=9000).
server:
  port: 8080
  read_timeout: 15s
  write_timeout: 15s

database:
  dsn: "host=db user=postgres password=password dbname=device_db port=5432 sslmode=disable"
  max_open_conns: 25
  max_idle_conns: 10
  conn_max_lifetime: 5m

redis:
  addr: "redis:6379"
  password: ""
  db: 0

service_bus:
  connection_string: "" # Add your Azure Service Bus connection string here
  queue_name: "device-messages"

firmware:
  storage_path: "/data/firmware"
  max_file_size: 10485760 # 10MB
  signing_enabled: false
  private_key_path: "" # e.g., /keys/private.pem

ota:
  chunk_size: 32768 # 32KB
  max_concurrent_updates: 50
  download_timeout: 10m
  retry_attempts: 3
