# services/device/config/config.yaml
# Default configuration for the device service.
# These values can be overridden by environment variables (e.g., DEVICE_SERVER__PORT=9000).
server:
  port: 8080
  read_timeout: 15s
  write_timeout: 15s

database:
  dsn: "host=db user=postgres password=password dbname=device_db port=5432 sslmode=disable"
  max_open_conns: 25
  max_idle_conns: 10
  conn_max_lifetime: 5m
  conn_max_idle_time: 10m
  enable_tracing: false

redis:
  addr: "redis:6379"
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  dial_timeout: 5s

service_bus:
  connection_string: "" # Not used directly anymore - see queue_routing
  queue_name: ""        # Not used directly anymore - see queue_routing
  max_retries: 3
  retry_delay: 1s

# MQTT configuration for telemetry ingestion
mqtt:
  broker_url: "tcp://mqtt-broker:1883" # Use tls:// for secure connections
  client_id: "device-service"
  username: ""
  password: ""
  qos: 1
  clean_session: false
  topics:
    - "devices/+/telemetry"      # Single device telemetry
    - "devices/+/telemetry/batch" # Batch telemetry
    - "devices/+/status"          # Device status updates
  keep_alive: 30s
  connect_timeout: 10s
  max_reconnect_delay: 2m

firmware:
  storage_path: "/data/firmware"
  max_file_size: 10485760 # 10MB
  signing_enabled: false
  private_key_path: "" # e.g., /keys/private.pem

ota:
  chunk_size: 32768 # 32KB
  max_concurrent_updates: 50
  download_timeout: 10m
  retry_attempts: 3

storage:
  wal_path: "/data/wal"
  dead_letter_path: "/data/dead_letter"
  backup_path: "/data/backup"
  retention_days: 30

# Queue routing configuration - maps organizations and telemetry types to Azure Service Bus queues
queue_routing:
  organizations:
    # Staging environments
    - organization_name: "staging.sandbox"
      environment: "staging"
      connection_string: "Endpoint=sb://local-test-service.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=kjzSKaOOBytm5Z8cwDZ5NKfQvkSlIBbX1NtLxhBEABY="
      queue_routes:
        - queue_name: "novek-staging-erp-messages-devices"
          telemetry_types: ["check", "location", "gps", "subscribe", "file-upload", "loc", "sensors"]
        - queue_name: "novek-staging-erp-aux-messages-devices"
          telemetry_types: ["net", "calibrate", "error", "audit_error", "audit_err", "echo", "selection", "mem", "storage_stat", "time", "ue_sysinfo", "settings"]
        - queue_name: "novek-staging-erp-messages-transactions"
          telemetry_types: ["prec", "drop", "pay", "subscribe", "refill", "auth-sys", "dispense"]
        - queue_name: "novek-staging-te-messages-transactions"
          telemetry_types: ["drop", "prec", "refund", "subscribe"]
        - queue_name: "novek-staging-cs-messages-canisters-sessions"
          telemetry_types: ["check", "can_refill", "can_refiller_entry", "can_refiller_exit", "cleanin-op-start", "cl-op-status", "cleaning-complete"]

    - organization_name: "staging.app.ingestor"
      environment: "staging"
      connection_string: "Endpoint=sb://staging-nvk-uksouth-ingestor-svcb.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=wpsyvmkLaD7K7I0pkV1jYIfr5D8JnKqiJl94RvsRWp8="
      queue_routes:
        - queue_name: "novek-staging-erp-messages-devices"
          telemetry_types: ["check", "location", "gps", "subscribe", "file-upload", "loc", "sensors"]
        - queue_name: "novek-staging-erp-aux-messages-devices"
          telemetry_types: ["net", "audit_error", "echo", "selection", "mem", "storage_stat", "time", "ue_sysinfo", "settings", "error"]
        - queue_name: "novek-staging-erp-messages-transactions"
          telemetry_types: ["prec", "drop", "pay", "subscribe", "refill", "auth-sys", "dispense"]
        - queue_name: "novek-staging-te-messages-transactions"
          telemetry_types: ["drop", "prec", "refund", "subscribe"]
        - queue_name: "novek-staging-dedicated-sales"
          telemetry_types: ["prec", "drop", "dispense"]
        - queue_name: "novek-staging-cs-messages-canisters-sessions"
          telemetry_types: ["check", "can_refill", "can_refiller_entry", "can_refiller_exit", "cleanin-op-start", "cl-op-status", "cleaning-complete"]

    # Production environments
    - organization_name: "Nestle Cloud"
      environment: "production"
      connection_string: "Endpoint=sb://production-nvk-uksouth-ingestor-svcb.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=1nGsG+Znzo0ftyyP/KTVNsaU4Z2CYbRIlPTcy/z0uWs="
      queue_routes:
        - queue_name: "nestle-production-erp-messages-devices"
          telemetry_types: ["check", "location", "gps", "subscribe", "file-upload", "loc"]
        - queue_name: "nestle-production-erp-aux-messages-devices"
          telemetry_types: ["audit_err", "audit_error", "echo", "error", "mem", "net", "time", "ue_sysinfo"]
        - queue_name: "nestle-production-erp-messages-transactions"
          telemetry_types: ["prec", "drop", "pay", "subscribe"]
        - queue_name: "nestle-production-te-messages-transactions"
          telemetry_types: ["drop", "prec", "refund", "subscribe"]

    - organization_name: "novek.app"
      environment: "production"
      connection_string: "Endpoint=sb://production-nvk-uksouth-ingestor-svcb.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=1nGsG+Znzo0ftyyP/KTVNsaU4Z2CYbRIlPTcy/z0uWs="
      queue_routes:
        - queue_name: "novek-production-erp-messages-devices"
          telemetry_types: ["check", "location", "gps", "subscribe", "file-upload", "loc", "sensors"]
        - queue_name: "novek-production-erp-aux-messages-devices"
          telemetry_types: ["mem", "error", "calibrate", "net", "selection", "settings", "storage_stat", "time"]
        - queue_name: "novek-production-erp-messages-transactions"
          telemetry_types: ["prec", "drop", "pay", "subscribe", "refill", "auth-sys", "dispense"]
        - queue_name: "novek-production-te-messages-transactions"
          telemetry_types: ["drop", "prec", "refund", "subscribe"]
        - queue_name: "novek-production-dedicated-sales"
          telemetry_types: ["drop", "dispense", "prec"]
        - queue_name: "novek-production-cs-messages-canisters-sessions"
          telemetry_types: ["check", "can_refill", "can_refiller_entry", "can_refiller_exit", "cleanin-op-start", "cl-op-status", "cleaning-complete"]