root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/device-service ./cmd"
bin = "tmp/device-service"
full_bin = "APP_ENV=dev APP_USER=air ./tmp/device-service serve"

include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_regex = ["_test.go"]
exclude_unchanged = true
follow_symlink = true
log = "air.log"
delay = 1000
stop_on_error = true
send_interrupt = false
kill_delay = 500

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

