# services/device/docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: device_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mqtt-broker:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"   # MQTT
      - "9001:9001"   # WebSocket
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-t", "$$SYS/#", "-C", "1", "-u", "health", "-P", "health"]
      interval: 10s
      timeout: 5s
      retries: 5

  device-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DEVICE_DATABASE__DSN: "host=db user=postgres password=password dbname=device_db port=5432 sslmode=disable"
      DEVICE_REDIS__ADDR: "redis:6379"
      DEVICE_MQTT__BROKER_URL: "tcp://mqtt-broker:1883"
      DEVICE_FIRMWARE__STORAGE_PATH: "/data/firmware"
    volumes:
      - device_data:/data
      - ./config/config.yaml:/app/config/config.yaml:ro
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      mqtt-broker:
        condition: service_healthy
    command: ["./device-service", "serve"]

  # Optional: MQTT Explorer for debugging
  mqtt-explorer:
    image: smeagolworms4/mqtt-explorer
    ports:
      - "4000:4000"
    environment:
      HTTP_PORT: 4000
      MQTT_BROKER_URL: mqtt-broker
      MQTT_BROKER_PORT: 1883
    depends_on:
      - mqtt-broker

volumes:
  postgres_data:
  redis_data:
  mosquitto_data:
  mosquitto_log:
  device_data:
